/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder */

#ifndef _Included_crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder
#define _Included_crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder
 * Method:    decodeNV21
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder_decodeNV21
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

/*
 * Class:     crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder
 * Method:    decodeYUY2
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder_decodeYUY2
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

/*
 * Class:     crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder
 * Method:    decodeYUY2
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_crimsonwoods_android_libs_cameraimagedecoder_CameraImageDecoder_decode422
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
